spring:
  datasource:
    username: root
    password: pass
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/site_maps_generator

  jpa.hibernate:
    show-sql: true
    ddl-auto: create
    database: mariadb
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
